# Use the official Node.js runtime as the base image
FROM node:24-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) to the container
COPY backend/package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy the rest of the application code to the container
COPY backend/ .

# Expose the port that the app runs on
EXPOSE $PORT

# Define the command to run the application
CMD [ "npm", "start" ]